Repository caddijp/frontend, pull requests merged in 2020-11, with the labels that each got.

#142 feat: add notifiaction component
  packages/components/src/Notification/Notification.ts
  packages/components/src/Notification/index.ts
  packages/components/src/index.ts
Labels: Type: Feature

#144 chore: bump v0.0.18
  CHANGELOG.md
  lerna.json
  packages/components/package.json
  packages/eslint-config/package.json
  packages/stylelint-config/package.json
  packages/tsconfig/package.json
Labels: Type: Release

#147 refactor(packages/components): use native onClick handlers
  package.json
  packages/components/src/Button/Button.tsx
  packages/components/tsconfig.build.json
  packages/components/tsconfig.esm.build.json
  packages/components/tsconfig.json
  packages/tsconfig/tsconfig.json
Labels: Type: Refactoring
