Repository caddijp/frontend, pull requests merged in 2020-10, with the labels that each got.

#3 tsconfig base
  packages/components/.storybook/main.js
  packages/components/__tests__/Button/__snapshots__/Button.stories.storyshot
  packages/components/__tests__/Table/__snapshots__/Table.stories.storyshot
  packages/components/src/Button/Button.stories.tsx
  packages/components/src/Modal/Modal.stories.tsx
  packages/components/src/Pagination/Pagination.stories.tsx
  packages/components/src/Table/Table.stories.tsx
  packages/components/tsconfig.build.json
  packages/tsconfig/README.md
  packages/tsconfig/package.json
  packages/tsconfig/tsconfig.json
  tsconfig.json
Labels: Type: Feature

#130 enhance button component
  packages/components/src/Form/Input.tsx
Labels: Type: Feature

#131 chore: bump v0.0.16
  CHANGELOG.md
  lerna.json
  packages/components/package.json
  packages/eslint-config/package.json
  packages/stylelint-config/package.json
  packages/tsconfig/package.json
Labels: Type: Release

#132 Update yarn.lock
  yarn.lock
Labels: Type: Bug

#133 chore: bump v0.0.17
  CHANGELOG.md
  lerna.json
  packages/components/package.json
  packages/eslint-config/package.json
  packages/stylelint-config/package.json
  packages/tsconfig/package.json
Labels: Type: Release

#134 fix: pin @types/react and @types/react-dom
  package.json
  yarn.lock
Labels: Type: Refactoring

#124 docs(readme): added install and usage, inspred standard-readme
  README.md
  packages/components/README.md
  packages/components/tsconfig.json
  packages/eslint-config/README.md
  packages/stylelint-config/README.md
  packages/tsconfig/README.md
  packages/tsconfig/package.json
Labels: Type: Documentation
