Repository caddijp/frontend, pull requests merged in 2020-09, with the labels that each got.

#72 chore: bump v0.0.13
  CHANGELOG.md
  lerna.json
  packages/components/package.json
  packages/eslint-config/package.json
  packages/stylelint-config/package.json
Labels: Type: Release

#73 fix: react versions
  packages/components/__tests__/Upload/__snapshots__/Upload.stories.storyshot
  yarn.lock
Labels: Type: Bug

#84 Update upload component
  packages/components/__tests__/Upload/__snapshots__/Upload.stories.storyshot
  packages/components/src/Upload/Upload.stories.tsx
  packages/components/src/Upload/Upload.tsx
Labels: Type: Feature

#86 chore: bump v0.0.14
  CHANGELOG.md
  lerna.json
  packages/components/package.json
  packages/eslint-config/package.json
  packages/stylelint-config/package.json
Labels: Type: Release

#91 feat: enhance modal component
  packages/components/src/Modal/Modal.tsx
Labels: Type: Feature

#92 fix: modal component
  packages/components/src/Modal/Modal.tsx
Labels: Type: Bug

#90 update button component
  packages/components/__tests__/Button/__snapshots__/story.storyshot
  packages/components/src/Button/Button.tsx
  packages/components/src/Button/story.tsx
Labels: Type: Feature

#94 chore: bump v0.0.15
  CHANGELOG.md
  lerna.json
  packages/components/package.json
  packages/eslint-config/package.json
  packages/stylelint-config/package.json
Labels: Type: Release
