Repository caddijp/frontend, pull requests merged in 2020-08, with the labels that each got.

#5 Introduce components
  .eslintrc.json
  .huskyrc
  .prettierrc
  .stylelintrc.json
  README.md
  commitlint.config.js
  package.json
  packages/components/.gitignore
  packages/components/README.md
  packages/components/package.json
  packages/components/src/components/Button/Button.tsx
  packages/components/src/components/Button/index.ts
  packages/components/src/index.ts
  packages/components/tsconfig.build.json
  packages/components/tsconfig.esm.build.json
  packages/components/tsconfig.json
  packages/eslint-config/index.js
  packages/eslint-config/package.json
  packages/stylelint-config/index.js
  packages/stylelint-config/package.json
  yarn.lock
Labels: Type: Feature

#6 feat: added prettier plugins
  .github/mergeable.yml
  .github/stale.yml
  package.json
  packages/components/package.json
  packages/eslint-config/package.json
  packages/stylelint-config/package.json
  yarn.lock
Labels: Type: Feature

#7 fix: registry urls
  lerna.json
  package.json
Labels: Type: Bug

#8 chore: bump v0.0.2
  .gitignore
  CHANGELOG.md
  lerna.json
  packages/components/package.json
  packages/eslint-config/package.json
  packages/stylelint-config/package.json
Labels: Type: Documentation

#9 fix: lint script
  package.json
  packages/components/package.json
Labels: Type: Bug

#10 chore: bump v0.0.3
  CHANGELOG.md
  lerna.json
  packages/components/package.json
  packages/eslint-config/package.json
  packages/stylelint-config/package.json
Labels: Type: Bug

#11 feat(components): upload component
  packages/components/package.json
  packages/components/src/components/Upload/Upload.tsx
  packages/components/src/components/Upload/index.ts
  packages/components/src/components/Upload/interface.d.ts
  packages/components/src/index.ts
  yarn.lock
Labels: Type: Feature

#12 feat(components): card component
  packages/components/src/components/Card/Card.tsx
  packages/components/src/components/Card/index.ts
  packages/components/src/index.ts
Labels: Type: Feature

#13 feat(components): button component
  packages/components/src/components/Button/Button.tsx
Labels: Type: Feature

#14 Feature form component
  packages/components/src/components/Form/Checkbox.tsx
  packages/components/src/components/Form/Input.tsx
  packages/components/src/components/Form/index.ts
  packages/components/src/index.ts
Labels: Type: Feature

#15 feat(components): caution component
  packages/components/src/components/Alert/Caution.tsx
  packages/components/src/components/Alert/index.ts
  packages/components/src/index.ts
Labels: Type: Feature

#16 chore: bump v0.0.4
  CHANGELOG.md
  lerna.json
  packages/components/package.json
  packages/eslint-config/package.json
  packages/stylelint-config/package.json
Labels: Type: Feature

#17 refactor: components directory
  .eslintignore
  .github/workflows/nodejs.yml
  .github/workflows/storybook.yml
  .gitignore
  .prettierignore
  .stylelintrc.json
  .yarnclean
  package.json
  packages/components/.gitignore
  packages/components/.storybook/config.tsx
  packages/components/__tests__/Storyshots.test.tsx
  packages/components/babel.config.js
  packages/components/package.json
  packages/components/src/Alert/Caution.tsx
  packages/components/src/Alert/index.ts
  packages/components/src/Button/Button.tsx
  packages/components/src/Button/__snapshots__/story.storyshot
  packages/components/src/Button/index.ts
  packages/components/src/Button/story.tsx
  packages/components/src/Card/Card.tsx
  packages/components/src/Card/index.ts
  packages/components/src/Form/Checkbox.tsx
  packages/components/src/Form/Input.tsx
  packages/components/src/Form/index.ts
  packages/components/src/Upload/Upload.tsx
  packages/components/src/Upload/index.ts
  packages/components/src/Upload/interface.d.ts
  packages/components/src/index.ts
  packages/components/tsconfig.build.json
  packages/components/tsconfig.esm.build.json
  packages/components/tsconfig.json
  packages/stylelint-config/example/sample.scss
  packages/stylelint-config/index.js
  packages/stylelint-config/package.json
  tsconfig.json
  yarn.lock
Labels: Type: Refactoring

#18 fix: tiny design
  packages/components/src/Form/Checkbox.tsx
  packages/components/src/Form/Input.tsx
Labels: Type: Bug

#19 chore: bump v0.0.5
  CHANGELOG.md
  lerna.json
  packages/components/package.json
  packages/eslint-config/package.json
  packages/stylelint-config/package.json
Labels: Type: Bug

#25 chore(packages/eslint-config): add custom rules
  packages/eslint-config/index.js
Labels: Type: Feature

#27 fix: style
  packages/components/src/Button/Button.tsx
  packages/components/src/Button/__snapshots__/story.storyshot
  packages/components/src/Button/story.tsx
  packages/components/src/Form/Input.tsx
Labels: Type: Bug

#28 feat: alert component
  packages/components/src/Alert/Alert.tsx
  packages/components/src/Alert/index.ts
Labels: Type: Feature

#29 chore: bump v0.0.6
  CHANGELOG.md
  lerna.json
  packages/components/package.json
  packages/eslint-config/package.json
  packages/stylelint-config/package.json
Labels: Type: Feature

#26 Add TextArea component
  packages/components/src/Form/TextArea.stories.tsx
  packages/components/src/Form/TextArea.tsx
  packages/components/src/Form/__snapshots__/TextArea.stories.storyshot
  packages/components/src/Form/index.ts
Labels: Type: Feature

#30 feat: text button component
  packages/components/src/Button/Button.tsx
  packages/components/src/Form/Checkbox.tsx
Labels: Type: Feature

#31 chore: bump v0.0.7
  CHANGELOG.md
  lerna.json
  packages/components/package.json
  packages/eslint-config/package.json
  packages/stylelint-config/package.json
Labels: Type: Feature

#32 docs: re-generate changelogs
  CHANGELOG.md
  packages/components/README.md
  packages/eslint-config/README.md
  packages/stylelint-config/README.md
Labels: Type: Documentation

#34 Add @storybook/addon-essentials
  packages/components/.storybook/config.tsx
  packages/components/.storybook/main.js
  packages/components/__tests__/Form/__snapshots__/TextArea.stories.storyshot
  packages/components/package.json
  yarn.lock
Labels: Type: Feature, Type: Refactoring

#36 fix: stories glob
  package.json
  packages/components/.storybook/main.js
  packages/components/__tests__/Button/__snapshots__/story.storyshot
  packages/components/babel.config.js
  packages/components/package.json
  packages/eslint-config/package.json
  yarn.lock
Labels: Type: Bug

#38 Create SECURITY.md
  SECURITY.md
Labels: Type: Documentation

#39 Add stories
  packages/components/.storybook/main.js
  packages/components/__tests__/Alert/__snapshots__/Alert.stories.storyshot
  packages/components/__tests__/Alert/__snapshots__/Caution.stories.storyshot
  packages/components/__tests__/Button/__snapshots__/story.storyshot
  packages/components/__tests__/Card/__snapshots__/Card.stories.storyshot
  packages/components/__tests__/Form/__snapshots__/Checkbox.stories.storyshot
  packages/components/__tests__/Form/__snapshots__/Input.stories.storyshot
  packages/components/__tests__/Upload/__snapshots__/Upload.stories.storyshot
  packages/components/src/Alert/Alert.stories.tsx
  packages/components/src/Alert/Alert.tsx
  packages/components/src/Alert/Caution.stories.tsx
  packages/components/src/Alert/Caution.tsx
  packages/components/src/Button/Button.tsx
  packages/components/src/Button/__snapshots__/story.storyshot
  packages/components/src/Button/story.tsx
  packages/components/src/Card/Card.stories.tsx
  packages/components/src/Card/Card.tsx
  packages/components/src/Form/Checkbox.stories.tsx
  packages/components/src/Form/Checkbox.tsx
  packages/components/src/Form/Input.stories.tsx
  packages/components/src/Form/Input.tsx
  packages/components/src/Form/TextArea.stories.tsx
  packages/components/src/Form/__snapshots__/TextArea.stories.storyshot
  packages/components/src/Upload/Upload.stories.tsx
Labels: Type: Testing

#33 impl modal component
  packages/components/__tests__/Storyshots.test.tsx
  packages/components/package.json
  packages/components/src/Modal/Modal.tsx
  packages/components/src/Modal/index.ts
  packages/components/src/Modal/story.tsx
  packages/components/src/index.ts
  yarn.lock
Labels: Type: Feature

#40 feat: add table component
  packages/components/__tests__/Table/__snapshots__/story.storyshot
  packages/components/src/Table/Table.tsx
  packages/components/src/Table/__snapshots__/story.storyshot
  packages/components/src/Table/index.ts
  packages/components/src/Table/story.tsx
  packages/components/src/index.ts
Labels: Type: Feature

#44 chore: use ts-jest
  package.json
  packages/components/babel.config.js
  packages/components/package.json
  yarn.lock
Labels: Type: Refactoring

#46 feat: add antd styles
  packages/components/.storybook/antd.styles.js
  packages/components/.storybook/main.js
  packages/components/.storybook/preview.js
  packages/components/package.json
  yarn.lock
Labels: Type: Feature

#45 refactor: we need storybook review :)
  .circleci/config.yml
Labels: Type: Refactoring

#42 Pagination Componentを実装
  package.json
  packages/components/.storybook/antd.styles.js
  packages/components/babel.config.js
  packages/components/package.json
  packages/components/src/Pagination/Pagination.tsx
  packages/components/src/Pagination/index.ts
  packages/components/src/Pagination/story.tsx
  packages/components/src/index.ts
  yarn.lock
Labels: Type: Feature

#47 chore: bump v0.0.8
  CHANGELOG.md
  lerna.json
  packages/components/package.json
  packages/eslint-config/package.json
  packages/stylelint-config/package.json
Labels: Type: Documentation

#48 fix: modal component
  packages/components/src/Modal/Modal.tsx
Labels: Type: Bug

#49 chore: bump v0.0.9
  CHANGELOG.md
  lerna.json
  packages/components/package.json
  packages/eslint-config/package.json
  packages/stylelint-config/package.json
Labels: Type: Release

#52 Feature/disable style for checkbox
  packages/components/__tests__/Form/__snapshots__/Checkbox.stories.storyshot
  packages/components/src/Form/Checkbox.stories.tsx
  packages/components/src/Form/Checkbox.tsx
Labels: Type: Feature

#53 fix: modal style
  packages/components/src/Modal/Modal.tsx
Labels: Type: Feature

#54 chore: bump v0.0.11
  CHANGELOG.md
  lerna.json
  packages/components/package.json
  packages/eslint-config/package.json
  packages/stylelint-config/package.json
Labels: Type: Release

#55 fix: checkbox type
  packages/components/src/Form/Checkbox.tsx
Labels: Type: Bug

#56 chore: bump v0.0.12
  CHANGELOG.md
  lerna.json
  packages/components/package.json
  packages/eslint-config/package.json
  packages/stylelint-config/package.json
Labels: Type: Release

#58 chore: update dependencies
  package.json
  packages/components/package.json
  packages/components/src/Alert/Alert.stories.tsx
  packages/components/src/Alert/Caution.stories.tsx
  packages/components/src/Button/story.tsx
  packages/components/src/Card/Card.stories.tsx
  packages/components/src/Form/Checkbox.stories.tsx
  packages/components/src/Form/Input.stories.tsx
  packages/eslint-config/package.json
  yarn.lock
Labels: Type: Feature
