Repository caddijp/frontend, pull requests merged in 2021-01, with the labels that each got.

#194 feat: add compressed-size
  .github/workflows/size.yml
Labels: Type: Refactoring

#202 feat(packages/components): add duration prop to Notification
  packages/components/.storybook/antd.styles.js
  packages/components/src/Notification/Notification.stories.tsx
  packages/components/src/Notification/Notification.ts
Labels: Type: Feature

#203 docs: bump v0.2.0
  CHANGELOG.md
  lerna.json
  packages/components/package.json
  packages/eslint-config/package.json
  packages/stylelint-config/package.json
  packages/tsconfig/package.json
Labels: Type: Documentation
